services:
  preprocess:
    command: bash -c 'echo ${USER_CONSENT} | python -m dataset_librarian.dataset -n brca --download --preprocess -d /workspace/data --split_ratio ${SPLIT_RATIO:-0.1}'
    environment:
      - USER_CONSENT=${USER_CONSENT}
      - SPLIT_RATIO=${SPLIT_RATIO-0.1}
    extends:
      service: dev

  hf-nlp-wf:
    build:
      context: ../hf_nlp/workflows/hf_finetuning_and_inference_nlp
    command: python src/run.py --config_file configs/${CONFIG:-nlp_finetune}.yaml 
    extends:
      service: dev
    image: intel/ai-workflows:pa-hf-nlp-disease-prediction
  vision-tlt-wf:
    build:
      context: ../vision_wf/workflows/disease_prediction
      dockerfile: ./Dockerfile
    command: python src/run.py --config_file configs/${CONFIG:-vision_finetune}.yaml 
    extends:
      service: dev
    image: intel/ai-workflows:pa-vision-tlt-disease-prediction
  ensemble-inference:
    command: python src/breast_cancer_prediction.py --config_file configs/${CONFIG:-disease_prediction_container}.yaml
    depends_on:
      hf-nlp-wf:
        condition: service_completed_successfully
      vision-tlt-wf:
        condition: service_completed_successfully
    extends:
      service: dev

  dev:
    build:
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
      context: ../
      dockerfile: ./docker/Dockerfile
    command: python ${SCRIPT:-src/breast_cancer_prediction.py} --config_file configs/${CONFIG:-disease_prediction_container}.yaml
    environment: 
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
    image: intel/ai-workflows:pa-disease-prediction
    privileged: true
    pull_policy: always
    volumes: 
      - /${DATASET_DIR:-$PWD/../data}:/workspace/data
      - /${CONFIG_DIR:-$PWD/../configs}:/workspace/configs
      - /${OUTPUT_DIR:-$PWD/../output}:/workspace/output
    working_dir: /workspace
