args:
  dataset: local
  dtype_ft: fp32
  dtype_inf: fp32
  finetune: true
  finetune_impl: itrex
  finetune_output: /data/datad/mcetin/brca_multimodal/src/../output/nlp/finetune_predictions_report.yaml
  infer_impl: itrex
  inference: true
  inference_output: inference_predictions_report.yaml
  local_dataset:
    delimiter: ','
    features:
      class_label: label
      data_column: symptoms
      id: Patient_ID
    finetune_input: /data/datad/mcetin/brca_multimodal/src/../data/annotation/training_data.csv
    inference_input: /data/datad/mcetin/brca_multimodal/src/../data/annotation/testing_data.csv
    label_list:
    - Benign
    - Malignant
    - Normal
  max_seq_len: 128
  max_test_samples: null
  max_train_samples: null
  model_name_or_path: emilyalsentzer/Bio_ClinicalBERT
  overwrite_cache: true
  pipeline: finetune
  preprocessing_num_workers: 32
  save_detailed_performance_metrics: true
  smoke_test: false
  tokenizer_name: emilyalsentzer/Bio_ClinicalBERT
training_args:
  do_predict: true
  do_train: true
  num_train_epochs: 12
  output_dir: /data/datad/mcetin/brca_multimodal/src/../output/nlp
  per_device_eval_batch_size: 256
  per_device_train_batch_size: 256
write: true
